export enum Skills {
  PrimeirosSocorros = "PRIMEIROS_SOCORROS",
  Comunicacao = "COMUNICACAO",
  TrabalhoEmEquipe = "TRABALHO_EM_EQUIPE",
  OrganizacaoDeEventos = "ORGANIZACAO_DE_EVENTOS",
  Culinaria = "CULINARIA",
  Transporte = "TRANSPORTE",
  Educacao = "EDUCACAO",
  SaudeMental = "SAUDE_MENTAL",
  ConstrucaoCivil = "CONSTRUCAO_CIVIL",
  Informatica = "INFORMATICA",
  Idiomas = "IDIOMAS",
  Fotografia = "FOTOGRAFIA",
  DesignGrafico = "DESIGN_GRAFICO",
  MidiasSociais = "MIDIAS_SOCIAIS",
  CaptacaoDeRecursos = "CAPTACAO_DE_RECURSOS",
  Jardinagem = "JARDINAGEM",
  CuidadoComAnimais = "CUIDADO_COM_ANIMAIS",
  Artesanato = "ARTESANATO",
  Lideranca = "LIDERANCA",
  Enfermagem = "ENFERMAGEM"
}